# Generated by Django 4.2.6 on 2023-10-22 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeStudentAccepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_number', models.IntegerField(default=0)),
                ('fullname', models.CharField(max_length=50)),
                ('school_year', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('grants', models.CharField(default='', max_length=10)),
                ('semester', models.CharField(default='', max_length=10)),
                ('remarks', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeStudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='Processing', max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='Unknown', max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(default='01-01-2001')),
                ('place_of_birth', models.CharField(default='', max_length=100)),
                ('contact_no', models.CharField(default='', max_length=25)),
                ('email_address', models.EmailField(default='', max_length=100)),
                ('school', models.CharField(default='', max_length=100)),
                ('course', models.CharField(default='', max_length=100)),
                ('gwa', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rank', models.IntegerField(default=0)),
                ('jhs', models.CharField(default='', max_length=100)),
                ('jhs_address', models.CharField(default='', max_length=100)),
                ('jhs_educational_provider', models.CharField(default='', max_length=100)),
                ('shs', models.CharField(default='', max_length=100)),
                ('shs_address', models.CharField(default='', max_length=100)),
                ('shs_educational_provider', models.CharField(default='', max_length=100)),
                ('father_voter_status', models.CharField(default='', max_length=100)),
                ('father_name', models.CharField(default='', max_length=100)),
                ('father_educational_attainment', models.CharField(default='', max_length=100)),
                ('father_occupation', models.CharField(default='', max_length=100)),
                ('father_employer', models.CharField(default='', max_length=100)),
                ('mother_voter_status', models.CharField(default='', max_length=100)),
                ('mother_name', models.CharField(default='', max_length=100)),
                ('mother_educational_attainment', models.CharField(default='', max_length=100)),
                ('mother_occupation', models.CharField(default='', max_length=100)),
                ('mother_employer', models.CharField(default='', max_length=100)),
                ('guardian_voter_status', models.CharField(default='', max_length=100)),
                ('guardian_name', models.CharField(default='', max_length=100)),
                ('guardian_educational_attainment', models.CharField(default='', max_length=100)),
                ('guardian_occupation', models.CharField(default='', max_length=100)),
                ('guardian_employer', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeStudentRejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_number', models.IntegerField(default=0)),
                ('fullname', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('school_year', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(default='', max_length=50)),
                ('req_a', models.CharField(default='False', max_length=100)),
                ('req_b', models.CharField(default='False', max_length=100)),
                ('req_c', models.CharField(default='False', max_length=100)),
                ('req_d', models.CharField(default='False', max_length=100)),
                ('req_e', models.CharField(default='False', max_length=100)),
                ('req_f', models.CharField(default='False', max_length=100)),
                ('req_g', models.CharField(default='False', max_length=100)),
                ('req_h', models.CharField(default='False', max_length=100)),
                ('req_i', models.CharField(default='False', max_length=100)),
                ('req_j', models.CharField(default='False', max_length=100)),
                ('req_k', models.CharField(default='False', max_length=100)),
                ('req_l', models.CharField(default='False', max_length=100)),
                ('req_m', models.CharField(default='False', max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('requirement_count', models.IntegerField(default=0)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.collegestudentapplication')),
            ],
        ),
    ]
