# Generated by Django 4.2.6 on 2023-10-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegerequirements',
            name='control_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
