# Generated by Django 4.2.6 on 2023-10-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegerequirements',
            name='requirement_count',
        ),
        migrations.AddField(
            model_name='collegerequirements',
            name='requirement',
            field=models.IntegerField(default=0),
        ),
    ]
