# Generated by Django 4.2.6 on 2023-10-22 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_collegerequirements_requirement_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegestudentapplication',
            name='status',
        ),
    ]
