# Generated by Django 4.2.6 on 2023-10-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_collegestudentapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegestudentaccepted',
            name='course',
        ),
        migrations.RemoveField(
            model_name='collegestudentaccepted',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='collegestudentaccepted',
            name='grants',
        ),
        migrations.RemoveField(
            model_name='collegestudentaccepted',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='collegestudentaccepted',
            name='school',
        ),
        migrations.RemoveField(
            model_name='collegestudentaccepted',
            name='semester',
        ),
        migrations.AlterField(
            model_name='collegestudentaccepted',
            name='school_year',
            field=models.CharField(default='1st Year', max_length=50),
        ),
    ]
