# Generated by Django 4.2.6 on 2023-10-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_collegerequirements_req_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegerequirements',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collegerequirements',
            name='req_1',
            field=models.CharField(default='False', max_length=100),
        ),
        migrations.AlterField(
            model_name='collegerequirements',
            name='req_2',
            field=models.CharField(default='False', max_length=100),
        ),
    ]
