# Generated by Django 4.2.6 on 2023-10-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_collegestudentrejected_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegestudentaccepted',
            name='id',
        ),
        migrations.RemoveField(
            model_name='collegestudentrejected',
            name='id',
        ),
        migrations.AlterField(
            model_name='collegestudentaccepted',
            name='control_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collegestudentrejected',
            name='control_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
