# Generated by Django 4.2.6 on 2023-10-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_financialassistanceapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='father_age',
            field=models.SmallIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='father_income',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='mother_age',
            field=models.SmallIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='mother_income',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='sibling_DOB',
            field=models.DateField(default='01-01-2001'),
        ),
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='sibling_age',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='financialassistanceapplication',
            name='sibling_count',
            field=models.SmallIntegerField(default=''),
        ),
    ]
